name: cursor28042025
description: "A social sports app for organizing and joining sports events."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  geolocator: ^10.1.0
  permission_handler: ^11.3.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/basketball.png
    - assets/soccer.png
    - assets/tennis.png
    - assets/basketball_court.jpg
    - assets/google_logo.png
